### ISSUE TITLE
No default user and register button does nothing.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [JordanKnott/taskcafe#151]
**Describe the bug**
Following `git clone https://github.com/JordanKnott/taskcafe && cd taskcafe` and then `docker-compose -p taskcafe up -d` the container starts successfully, but there is no default user, register button does nothing and there is no setup page. The whole thing is ready to go.

**Expected behavior**
To be able to have a default user, or at the very least a setup page where I can create the default user.

**Screenshots / Live demo link**
![image](https://user-images.githubusercontent.com/3938423/160350910-ba7eedf0-95e8-4866-8b51-1e2e5b9c7d3f.png)

**Comment by Unrepentant-Atheist** [comment]
Anybody??

**Comment by chris-ti-an-g** [comment]
did you try this?
https://github.com/JordanKnott/taskcafe/issues/141#issuecomment-1041023938

**Comment by kenbai** [comment]
same to me

**Comment by Ioridy** [comment]
> did you try this? [#141 (comment)](https://github.com/JordanKnott/taskcafe/issues/141#issuecomment-1041023938)

thank you for your information, this can direct to register page and create a new account.

**Comment by boomam** [comment]
Same for me too, same workaround of going to /register.

**Comment by mbetrifork** [comment]
+1 here. Does not work out of the box, stuck at the login/register screen.

**Comment by Polluxe** [comment]
```
version: "3"
services:
  web:
    image: taskcafe/taskcafe:latest
    # build: .
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - taskcafe-test
    environment:
      TASKCAFE_DATABASE_HOST: postgres
      TASKCAFE_MIGRATE: "true"
    volumes:
      - taskcafe-uploads:/root/uploads
      
  postgres:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - taskcafe-test
    environment:
      POSTGRES_USER: taskcafe
      POSTGRES_PASSWORD: taskcafe_test
      POSTGRES_DB: taskcafe
    volumes:
      - taskcafe-postgres:/var/lib/postgresql/data

  migrate:
    build: .
    entrypoint: ./taskcafe migrate
    volumes:
      - ./migrations:/root/migrations
    depends_on:
      - postgres
    networks:
      - taskcafe-test

volumes:
  taskcafe-postgres:
    external: false
  taskcafe-uploads:
    external: false

networks:
  taskcafe-test:
    driver: bridge
```
i change docker-compose.yml to this, and work , then i regist

**Comment by ghost** [comment]
expose the postgres from the compose to localhost like that
```
  postgres:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - taskcafe-test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: taskcafe
      POSTGRES_PASSWORD: taskcafe_test
      POSTGRES_DB: taskcafe
    volumes:
      - taskcafe-postgres:/var/lib/postgresql/data
```
Then connect to posgres 
```
psql -h 127.0.0.1 -U taskcafe  taskcafe
```
and change the password for the default 'system' user to be 'system' like that
```
update user_account set password_hash='$2a$14$H9eK2TnWwyS9WEjGN9RN3.cmKv6jy6fRadQNnLRw8Fm4n7psAeoMy';

```
