### ISSUE TITLE
[HELP] Dirty database version 1.

### ISSUE THREAD

**Issue by mzch** [JordanKnott/taskcafe#54]
**Describe the bug**
I built a binary and tried to `taskcafe migrate`, but failed.

```sh
taskcafe@n24:~/bin$ ./taskcafe migrate
Error: Dirty database version 1. Fix and force version.
Usage:
  taskcafe migrate [flags]

Flags:
  -h, --help   help for migrate

Global Flags:
      --config string   config file path
```

Could anyone tell me how to fix this issue?

- taskcafe.toml
```toml
[general]
host = '127.0.0.1:3333'

[email_notifications]
enabled = true
display_name = "TaskCafe"
from_address = "no-reply@example.com"

[storage]
storage_system = 'local_storage'
upload_dir_path = '/srv/taskcafe/uploads'

[database]
host = '192.168.207.11'
name = 'taskcafe'
user = 'taskcafe'
password = 'password'

[smtp]
username = 'admin@example.com'
password = 'password'
server = 'mx1.mail-services.net'
port = 587
connection_security = 'STARTTLS'
```

**Expected behavior**
Taskcafe will make a migration of database successfully.

**Screenshots / Live demo link**
None.

**Additional context**
None.
