### ISSUE TITLE
taskcafe.example.toml lacks server.hostname 

### ISSUE THREAD

**Issue by mzch** [JordanKnott/taskcafe#59]
**Describe the bug**
In taskcafe.example.toml, there is:
```toml
[general]
host = '0.0.0.0:3333'
```
but this is no sense. It should be
```toml
[server]
hostname = '0.0.0.0:3333'
```

**Expected behavior**
Change taskcafe.example.toml

**Screenshots / Live demo link**
None

**Additional context**
None.

**Comment by JordanKnott** [comment]
Thanks for the issue, but I prefer `host` for the time being. If I split out the port and the IP I might rename it

**Comment by mzch** [comment]
But in `internal/commands/web.go` the code is `http.ListenAndServe(viper.GetString("server.hostname"), r)`

**Comment by JordanKnott** [comment]
Oh! Guess I preferred hostname after all :smile: - I'll update the config

**Comment by mzch** [comment]
Oh, is this in the `[server]` section?

```toml
[server]
hostname = '0.0.0.0:3333'
```
