### ISSUE TITLE
Taskcafe PostgreSQL Port

### ISSUE THREAD

**Issue by DrAg0n141** [JordanKnott/taskcafe#78]
Hello,

i need to change the postgresql port to another, what ENV is the right one? I have tested TASKCAFE_DATABASE_HOST_PORT but it is not working. 

Thanks for your help.

DrAg0n141

**Comment by jpdsceu** [comment]
In docker-compose.yml, add in bold.

```
  postgres:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - taskcafe-test
   **ports:
      -'YOURPORT:5432'**
    environment:
      POSTGRES_USER: taskcafe
      POSTGRES_PASSWORD: taskcafe_test
      POSTGRES_DB: taskcafe
    volumes:
    - taskcafe-postgres:/var/lib/postgresql/data
```
This method will only work if `TASKCAFE_DATABASE_HOST_PORT` is a valid environment.
